# Generated by Django 5.0.7 on 2024-08-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page_deli', '0002_brand_servicecasemeats_plu_servicecasemeats_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecasemeats',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecasemeats',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
