# Generated by Django 5.0.7 on 2024-08-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page_deli', '0003_alter_servicecasemeats_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotcase',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='first_page_deli.category'),
        ),
    ]
