# Generated by Django 5.0.7 on 2024-08-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page_deli', '0006_alter_cheeseboard_category_alter_dips_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheeseboard',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='dips',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='entertainmentend',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='hotcase',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='packedmeati',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='packedmeatii',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='pizzaandsalads',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='saladsend',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='sandwichendi',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='sandwichendii',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='servicecasemeats',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='servicecasemeats',
            name='item_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecasemeats',
            name='plu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecasesalads',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
        migrations.AlterField(
            model_name='soupsandmeals',
            name='category',
            field=models.ManyToManyField(blank=True, to='first_page_deli.category'),
        ),
    ]
