# Generated by Django 5.0.7 on 2024-08-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page_deli', '0007_alter_cheeseboard_category_alter_dips_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaCheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crust_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaToppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('category', models.ManyToManyField(blank=True, to='first_page_deli.category')),
                ('cheese', models.ManyToManyField(to='first_page_deli.pizzacheese')),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_page_deli.pizzacrust')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_page_deli.pizzasauce')),
                ('toppings', models.ManyToManyField(to='first_page_deli.pizzatoppings')),
            ],
        ),
    ]
