# Generated by Django 5.0.7 on 2024-08-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page_deli', '0008_pizzacheese_pizzacrust_pizzasauce_pizzatoppings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaMeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='meat',
            field=models.ManyToManyField(blank=True, to='first_page_deli.pizzameat'),
        ),
    ]
