# Generated by Django 5.0.7 on 2024-08-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page_deli', '0010_pizzasize_pizza_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
