# Generated by Django 5.0.7 on 2024-08-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_page_deli', '0012_alter_entertainmentend_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entertainmentend',
            options={'verbose_name': 'Entertainment End', 'verbose_name_plural': 'Entertainment End'},
        ),
    ]
