# Generated by Django 5.0.7 on 2024-08-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_page_deli', '0013_alter_entertainmentend_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sandwichendi',
            options={'verbose_name': 'Sandwich End - I', 'verbose_name_plural': 'Sandwich End - I'},
        ),
        migrations.AlterModelOptions(
            name='sandwichendii',
            options={'verbose_name': 'Sandwich End - II', 'verbose_name_plural': 'Sandwich End - II'},
        ),
    ]
