# Generated by Django 5.0.7 on 2024-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page_deli', '0014_alter_sandwichendi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BYOPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
