# Generated by Django 5.0.7 on 2024-09-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page_deli', '0015_byopizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSaleMeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale_meats', models.ManyToManyField(blank=True, to='first_page_deli.servicecasemeats')),
            ],
        ),
        migrations.CreateModel(
            name='OnSaleSalads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale_salads', models.ManyToManyField(blank=True, to='first_page_deli.servicecasesalads')),
            ],
        ),
    ]
